TheJoeFin/Text-Grab

- Text-Grab/App.xaml.cs
- Text-Grab/MainWindow.xaml.cs
Still having issues when multiple displays are different sizes and have different scaling factors.
> Initial Multi monitor attempt

- README.md
- Fixed typo "Text Grab wroks..."
> fixed typo in header

- Text-Grab/Utilities/StringMethods.cs
1. Removed a small amount of redundant code.
2. Used StringBuilder methods rather than string concatenation when available.
> Minor improvements in string methods

- Text-Grab/Views/EditTextWindow.xaml.cs
Dispose the FontDialog instance
> Dispose FontDialog

- Text-Grab/Utilities/WindowResizer.cs
Fix 2 sites that may raise null ref exceptions.
> Fix 2 possible null reference errors

- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Utilities/StringMethods.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
Minor tweaks to remove superfluous conversion of arrays to lists
> Remove superfluous conversions

- Text-Grab/Views/GrabFrame.xaml.cs
This code seems redundant to me.
> Remove redundant code

- Text-Grab/Views/FullscreenGrab.xaml.cs
Fixes #46
Works on devices with different scaling.
> Move selection region when pressing shift

- Text-Grab/App.xaml.cs
Create a point at which we can catch and log unhandled exceptions.
> Catch unhandled exceptions and log to console before shutdown.

- Text-Grab/Utilities/ImageMethods.cs
Extracted duplicate code block into a new "GetOCRLanguage" method.
> Refactor - extract duplicate code into function

- Text-Grab/OSInterop.cs
- Text-Grab/Utilities/CursorClipper.cs
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/GrabFrame.xaml.cs
Constrain mouse cursor during drag selection (both full-screen and grab frame).
> Replace PR #90

- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
> Shows suggested spelling corrections in context menu

- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
Adds a top-level Capture Menu Item
- New Fullscreen Grab
- New Grab Frame
Fixes #83
> Add Capture Menu Item

- Text-Grab/Utilities/StringMethods.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
> Unstack string method

- Text-Grab/Utilities/StringMethods.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
> Create Remove Duplicate Lines method and connect to Menu Item

- Text-Grab/App.xaml
- Text-Grab/App.xaml.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/HotKeyManager.cs
- Text-Grab/Utilities/NotifyIconUtilities.cs
- Text-Grab/Utilities/WindowUtilities.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/FirstRunWindow.xaml
- Text-Grab/Views/FirstRunWindow.xaml.cs
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
Fixes #122
Fixes #58  
Fixes #30
Fixes #4
> Add Background Process via NotifyIcon

- Text-Grab-Package/Text-Grab-Package.wapproj
- Text-Grab/Text-Grab.csproj
> Upgrade to .net6

- Text-Grab-Package/Package.appxmanifest
- Text-Grab/App.xaml.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
This enables startup on login to occur and handles the first launch when the background task is enabled.
> Startup on login option

- Text-Grab/Controls/WordBorder.xaml
- Text-Grab/Controls/WordBorder.xaml.cs
- Text-Grab/Models/ResultTable.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Styles/ButtonStyles.xaml
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Utilities/NumberExtensions.cs
- Text-Grab/Utilities/WindowUtilities.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/FullscreenGrab.xaml
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
Grab Frame can now,
- Read Tables
- Freeze view
- Edit Words
- Quickly zoom
- Open Images with Drop
Fix #11
Fix #140 
Fix #139 
Fix #136 
Fix #135 
Fix #121 
Fix #86
> Many Awesome Grab Frame Features like Tables

- Text-Grab/Controls/AddOrRemoveWindow.xaml
- Text-Grab/Controls/AddOrRemoveWindow.xaml.cs
- Text-Grab/Enums.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
> Add "Add or remove window"

- Text-Grab/App.config
- Text-Grab/Controls/WordBorder.xaml
- Text-Grab/Controls/WordBorder.xaml.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/FullscreenGrab.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
Add the ability to read barcodes 
Closes #195
> Read qr and barcodes

- Text-Grab/App.xaml.cs
- Text-Grab/Models/AsyncOcrFileResult.cs
- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/app.manifest
closes #179 
Now there are two buttons.
1. OCR Every image in a folder
2. Write a .txt file for every image in a folder
Before doing the work a dialog box asks if the user wants to read every sub folder as well
The work is now done in batches of 6 at a time in parallel.
> OCR Every Image in a directory now better

- Text-Grab/Controls/WordBorder.xaml
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/QuickSimpleLookup.xaml
- Text-Grab/Views/QuickSimpleLookup.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
When adding a tab to the QSL Seachbox this initiates the "Add Item" button which will add a new item to the Lookup items
> QSL better items inputting

- Tests/OcrTests.cs
- Tests/StringMethodTests.cs
- Text-Grab/App.xaml.cs
- Text-Grab/Controls/FindAndReplaceWindow.xaml.cs
- Text-Grab/Models/OcrDirectoryOptions.cs
- Text-Grab/Utilities/StringMethods.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/OcrDirectoryOptions.cs
Closes #301 
Closes #302 
Closes #292
> Etw small tweaks

- Text-Grab/App.config
- Text-Grab/App.xaml.cs
- Text-Grab/Controls/WordBorder.xaml.cs
- Text-Grab/Enums.cs
- Text-Grab/Extensions/ShapeExtensions.cs
- Text-Grab/Models/HistoryInfo.cs
- Text-Grab/Models/WordBorderInfo.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Services/HistoryService.cs
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Utilities/NotifyIconUtilities.cs
- Text-Grab/Utilities/OcrExtensions.cs
- Text-Grab/Utilities/Singleton.cs
- Text-Grab/Utilities/StringMethods.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/FirstRunWindow.xaml.cs
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
> Add History to Text Grab

- Text-Grab/Utilities/FileUtilities.cs
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
> Improvements on grab frame

- Tests/FilesIoTests.cs
- Tests/OcrTests.cs
- Text-Grab/Enums.cs
- Text-Grab/Services/HistoryService.cs
- Text-Grab/Utilities/FileUtilities.cs
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/GrabFrame.xaml.cs
- Text-Grab/Views/QuickSimpleLookup.xaml.cs
> All platform file io

- .github/workflows/buildDev.yml
- Tests/OcrTests.cs
- Tests/QrCodeTests.cs
- Tests/Tests.csproj
- Text-Grab-Package/Package.appxmanifest
- Text-Grab/App.config
- Text-Grab/Controls/QrCodeWindow.xaml
- Text-Grab/Controls/QrCodeWindow.xaml.cs
- Text-Grab/Interfaces/ILanguage.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/BarcodeUtilities.cs
- Text-Grab/Utilities/LanguageUtilities.cs
- Text-Grab/Utilities/OcrUtilities.cs
- Text-Grab/Utilities/TesseractHelper.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/FullscreenGrab.xaml
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
- Improve Tesseract support
- Better language support
- Better support for any location
- winget commands in settings
- Full Screen Grab now only shows toolbars when mouse is over that screen
- Update packages as always
> Merging 4.2 dev into main

- Tests/Tests.csproj
- Text-Grab/App.config
- Text-Grab/Controls/CollapsibleButton.xaml
- Text-Grab/Controls/CollapsibleButton.xaml.cs
- Text-Grab/Controls/ShortcutControl.xaml
- Text-Grab/Controls/ShortcutControl.xaml.cs
- Text-Grab/Controls/WordBorder.xaml
- Text-Grab/Models/ShortcutKeySet.cs
- Text-Grab/NativeMethods.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Services/HistoryService.cs
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/HotKeyManager.cs
- Text-Grab/Utilities/NotifyIconUtilities.cs
- Text-Grab/Utilities/OcrUtilities.cs
- Text-Grab/Utilities/ShortcutKeysUtilities.cs
- Text-Grab/Views/EditTextWindow.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
- Text-Grab/Views/SettingsWindow.xaml.cs
closes #330
closes #329 
closes #328 
closes #327 
closes #279
closes #381
> Custom Shortcuts/Hotkeys

- Text-Grab/Utilities/TesseractHelper.cs
> Add UTF8 Encoding to Tesseract calls

- README.md
> Add chocolatey install option to README.MD

- Tests/ScreenLayoutTests.cs
- Text-Grab/Extensions/DapploExtensions.cs
- Text-Grab/NativeMethods.cs
- Text-Grab/Text-Grab.csproj
- Text-Grab/Utilities/WindowUtilities.cs
- Text-Grab/Views/FullscreenGrab.xaml.cs
use Dapplo instead of WinForms Screens
> Dapplo screens

- Text-Grab/App.config
- Text-Grab/Controls/CollapsibleButton.xaml
- Text-Grab/Models/LookupItem.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Services/HistoryService.cs
- Text-Grab/Styles/ButtonStyles.xaml
- Text-Grab/Styles/DataGridStyles.xaml
- Text-Grab/Styles/TextBoxStyles.xaml
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/QuickSimpleLookup.xaml
- Text-Grab/Views/QuickSimpleLookup.xaml.cs
> Search history from qsl

- .editorconfig
- Text-Grab/App.config
- Text-Grab/Controls/WordBorder.xaml.cs
- Text-Grab/Controls/ZoomBorder.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Text-Grab.csproj
- Text-Grab/UndoRedoOperations/AddWordBorder.cs
- Text-Grab/UndoRedoOperations/ChangedImage.cs
- Text-Grab/UndoRedoOperations/Operation.cs
- Text-Grab/UndoRedoOperations/RemoveWordBorder.cs
- Text-Grab/UndoRedoOperations/UndoRedo.cs
- Text-Grab/Utilities/ImageMethods.cs
- Text-Grab/Utilities/MagickHelpers.cs
- Text-Grab/Views/GrabFrame.xaml
- Text-Grab/Views/GrabFrame.xaml.cs
- Text-Grab/Views/MagickHelpers.cs
- Invert
- Grayscale
- Increase contrast
- Brighten
- Darken
> Edit the Grab Frame Image

- Text-Grab/App.config
- Text-Grab/Controls/BottomBarSettings.xaml
- Text-Grab/Controls/BottomBarSettings.xaml.cs
- Text-Grab/Controls/LanguagePicker.xaml
- Text-Grab/Controls/LanguagePicker.xaml.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Utilities/IoUtilities.cs
- Text-Grab/Utilities/LanguageUtilities.cs
- Text-Grab/Views/EditTextWindow.xaml
- Text-Grab/Views/EditTextWindow.xaml.cs
> ETW Language Picker and Spelling

- Text-Grab/App.config
- Text-Grab/Enums.cs
- Text-Grab/Pages/FullscreenGrabSettings.xaml
- Text-Grab/Pages/FullscreenGrabSettings.xaml.cs
- Text-Grab/Properties/Settings.Designer.cs
- Text-Grab/Properties/Settings.settings
- Text-Grab/Styles/ButtonStyles.xaml
- Text-Grab/Styles/DataGridStyles.xaml
- Text-Grab/Styles/TextBoxStyles.xaml
- Text-Grab/Views/FullscreenGrab.xaml.cs
- Text-Grab/Views/SettingsWindow.xaml
Add more settings for the Fullscreen Grab in it's own page
closes #531 
closes #524 
closes #518
> Fsg settings

- global.json
> Add a global.json file to keep the build script from using net10
